name: Accessibility Lint

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    paths:
      - 'layout/**/*.liquid'
      - 'sections/**/*.liquid'
      - 'snippets/**/*.liquid'
      - 'blocks/**/*.liquid'
      - 'templates/**/*.liquid'
      - 'templates/**/*.json'

jobs:
  a11y-lint:
    name: Static a11y lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run accessibility linter
        uses: scale-media/a11y-lint-action@v1
        continue-on-error: true
